# Generated by Django 5.2.12 on 2026-08-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='OVIU', max_length=100)),
                ('store_tagline', models.CharField(blank=True, max_length=200)),
                ('store_email', models.EmailField(blank=True, max_length=254)),
                ('store_phone', models.CharField(blank=True, max_length=30)),
                ('store_address', models.CharField(blank=True, max_length=255)),
                ('store_description', models.CharField(blank=True, max_length=500)),
                ('primary_color', models.CharField(default='#0F0F0F', max_length=7)),
                ('secondary_color', models.CharField(default='#C89072', max_length=7)),
                ('background_color', models.CharField(default='#F7F2EE', max_length=7)),
                ('enable_multilanguage', models.BooleanField(default=False)),
                ('enable_low_stock_alerts', models.BooleanField(default=True)),
                ('enable_dark_mode', models.BooleanField(default=False)),
                ('enable_chatbot', models.BooleanField(default=True)),
                ('enable_wishlist', models.BooleanField(default=True)),
                ('enable_marketing_messages', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
