# Generated by Django 5.2.12 on 2026-04-18 22:23

import django.core.validators
import django.db.models.deletion
import try_on.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TryOnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Original user photo', upload_to=try_on.models.tryon_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('glasses_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tryon_images', to='products.product')),
            ],
            options={
                'verbose_name': 'Try-On Image',
                'verbose_name_plural': 'Try-On Images',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TryOnSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tryon_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Try-On Session',
                'verbose_name_plural': 'Try-On Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TryOnResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_image', models.ImageField(help_text='Image with glasses applied', upload_to=try_on.models.tryon_result_upload_path)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence score (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='try_on.tryonimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_results', to='products.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='try_on.tryonsession')),
            ],
            options={
                'verbose_name': 'Try-On Result',
                'verbose_name_plural': 'Try-On Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tryonimage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='try_on.tryonsession'),
        ),
        migrations.CreateModel(
            name='FaceMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_distance', models.FloatField(help_text='Distance between eyes in mm (30-80mm)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(80)])),
                ('face_width', models.FloatField(help_text='Face width in mm (100-200mm)', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(200)])),
                ('nose_bridge', models.FloatField(blank=True, help_text='Nose bridge width in mm (5-30mm) - optional', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='try_on.tryonsession')),
            ],
            options={
                'verbose_name': 'Face Measurement',
                'verbose_name_plural': 'Face Measurements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tryonsession',
            index=models.Index(fields=['session_key', '-created_at'], name='try_on_tryo_session_dd3de0_idx'),
        ),
        migrations.AddIndex(
            model_name='tryonsession',
            index=models.Index(fields=['user', '-created_at'], name='try_on_tryo_user_id_4381b7_idx'),
        ),
        migrations.AddIndex(
            model_name='tryonresult',
            index=models.Index(fields=['session', '-created_at'], name='try_on_tryo_session_db40c1_idx'),
        ),
        migrations.AddIndex(
            model_name='tryonresult',
            index=models.Index(fields=['product', '-created_at'], name='try_on_tryo_product_ef0ea5_idx'),
        ),
    ]
