# Generated by Django 5.2.12 on 2026-07-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='governorates',
            field=models.JSONField(blank=True, default=list, help_text='قائمة المحافظات المسموح بها لاستخدام الكوبون (فارغة = كل المحافظات)'),
        ),
    ]
