# Generated by Django 5.2.12 on 2026-07-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='governorate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='governorate'),
        ),
    ]
