# Generated by Django 5.2.12 on 2026-07-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_admin_reply',
            field=models.BooleanField(default=False, help_text='True لو الرد ده كتبه أدمن حقيقي مش البوت'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='هل تم إغلاق المحادثة من الأدمن'),
        ),
    ]
