# Generated by Django 5.2.12 on 2026-07-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='رد الأدمن على التقييم'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='رفض المشرف للتقييم'),
        ),
    ]
