# Generated by Django 5.2.12 on 2026-05-12 03:46

import try_on.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try_on', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryonresult',
            name='processed_image',
            field=models.ImageField(blank=True, help_text='Image with glasses applied', null=True, upload_to=try_on.models.tryon_result_upload_path),
        ),
    ]
