# Generated by Django 5.2.12 on 2026-05-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_review'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_type_f73814_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='audience',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='frame_shape',
            field=models.CharField(blank=True, choices=[('round', 'Round'), ('square', 'Square'), ('rectangle', 'Rectangle'), ('aviator', 'Aviator'), ('cat_eye', 'Cat Eye')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lens_type',
            field=models.CharField(blank=True, choices=[('glass', 'Glass'), ('plastic', 'Plastic'), ('blue_cut', 'Blue Cut'), ('contact', 'Contact Lens')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('medical', 'Medical Glasses'), ('sunglasses', 'Sunglasses'), ('reading', 'Reading Glasses'), ('lenses', 'Lenses')], default='medical', max_length=50),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'audience'], name='products_pr_product_842a60_idx'),
        ),
    ]
