# Generated by Django 5.2.12 on 2026-08-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.AddField(
            model_name='color',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
